// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWFwpD1kQDINa5xidof-EgHf-iJArx2aY',
    appId: '1:246455976925:web:5f6ef274f550bdac322c34',
    messagingSenderId: '246455976925',
    projectId: 'chat-app-49e43',
    authDomain: 'chat-app-49e43.firebaseapp.com',
    storageBucket: 'chat-app-49e43.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAT_ie9Cro35zck4ZgK223JFGApScETqAc',
    appId: '1:246455976925:android:2d2b65076eba2647322c34',
    messagingSenderId: '246455976925',
    projectId: 'chat-app-49e43',
    storageBucket: 'chat-app-49e43.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDJex7QKpW98yrhcM2d-FqW1fEYjFmZRmI',
    appId: '1:246455976925:ios:9051c0e3b0cd9308322c34',
    messagingSenderId: '246455976925',
    projectId: 'chat-app-49e43',
    storageBucket: 'chat-app-49e43.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDJex7QKpW98yrhcM2d-FqW1fEYjFmZRmI',
    appId: '1:246455976925:ios:9051c0e3b0cd9308322c34',
    messagingSenderId: '246455976925',
    projectId: 'chat-app-49e43',
    storageBucket: 'chat-app-49e43.appspot.com',
    iosBundleId: 'com.example.chat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDWFwpD1kQDINa5xidof-EgHf-iJArx2aY',
    appId: '1:246455976925:web:82211405e43db84e322c34',
    messagingSenderId: '246455976925',
    projectId: 'chat-app-49e43',
    authDomain: 'chat-app-49e43.firebaseapp.com',
    storageBucket: 'chat-app-49e43.appspot.com',
  );
}
